apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-publisher
spec:
  selector:
    matchLabels:
      app: pubsub-publisher
  template:
    metadata:
      labels:
        app: pubsub-publisher
    spec:
      volumes:
      - name: google-cloud-keys
        secret:
          secretName: gac-keys
      containers:
      - name: publisher
        image: gcr.io/exchnage-pubsub/exchange-pubsub-exch-publisher:latest
        volumeMounts:
        - name: google-cloud-keys
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/exchnage-pubsub-sa-V2.json
