apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-subscriber-chf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-subscriber-chf
  template:
    metadata:
      labels:
        app: pubsub-subscriber-chf
    spec:
      volumes:
      - name: google-cloud-keys
        secret:
          secretName: gac-keys
      containers:
      - name: subscriber-chf
        image: gcr.io/exchnage-pubsub/exchange-pubsub-exch-subscriber:latest
        volumeMounts:
        - name: google-cloud-keys
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/exchnage-pubsub-sa-V2.json
        - name: TOPIC_ID
          value: "exch_CHFPLN"
        - name: EXCH_URL
          value: "https://internetowykantor.pl/kurs-franka/"
        - name: SUBSCRIPTION_ID
          value: "sub_CHFPLN"